# Generated by Django 4.0.4 on 2022-05-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonim', max_length=20)),
                ('post', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
